# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSTutorial
  pod 'SQLite.swift', '~> 0.13.0'
  pod 'SwiftLint'
  pod 'NotificationBannerSwift'
  pod 'ReachabilitySwift'

  target 'iOSTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSTutorialUITests' do
    # Pods for testing
  end

end
