# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alamofire ExampleOne' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alamofire ExampleOne
pod 'Alamofire'
pod 'ObjectMapper', '~> 3.4'
pod 'PromiseKit'
pod 'AlamofireImage'
end
