# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GNRLIb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GNRLIb
pod 'STAdvertisementLib', :git => 'https://github.com/arifparvez14/STAdvertisementLib.git', :tag => '0.0.6'

end
