# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alamofire with Table View' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alamofire with Table View
	pod 'SwiftyJSON'

pod 'Alamofire'

pod 'AlamofireImage'



end
