# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OPenWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PKHUD'
  pod 'Alamofire'

  target 'OPenWeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OPenWeatherAppUITests' do
    # Pods for testing
  end

end
