# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PKHUD'
  pod 'Alamofire'
  # Pods for OpenWeatherApp

end
